version: '3.1'

services:

  server:
    container_name: blog-server
    image: ghcr.io/jakub-spiewak/jakubspiewak-blog-server:latest
#    restart: on-failure
    ports:
      - "9000:8080"
    depends_on:
      - mongo

  mongo:
    container_name: blog-mongodb
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root1
      - MONGO_INITDB_DATABASE=blog-counter
